### PR TITLE
Repair pre-commit CI

### PR DESCRIPTION
**Pull request by crusaderky**
The pre-commit CI job has recently started misbehaving due to the upgrade of ubuntu-latest from 22.04 to 24.04.
e.g. https://github.com/deshaw/versioned-hdf5/actions/runs/11348180310/job/31561463192?pr=380

### CODE REVIEW

**Comment by peytondmurray** [comment]
Saw this last night as well. It sounds like for some reason switching to 24.04 causes `actions/setup-python` to _not_ install python if one is already found on $PATH (???), which I guess was not the case for 22.04 (but is for 24.04). Instead of pinning to an older image, I think moving forward we will need to explicitly request for

```
with:
  python-version: 3.x
```

as seen here: https://github.com/pre-commit/action/issues/210

**Review by peytondmurray — COMMENTED** [review]
Saw this last night as well. It sounds like for some reason switching to 24.04 causes actions/setup-python to not install python if one is already found on $PATH (???), which I guess was not the case for 22.04 (but is for 24.04). Instead of pinning to an older image, I think moving forward we will need to explicitly request for

with:
  python-version: 3.x

as seen here: https://github.com/pre-commit/action/issues/210. Thoughts?

**Comment by crusaderky** [comment]
> Saw this last night as well. It sounds like for some reason switching to 24.04 causes actions/setup-python to not install python if one is already found on $PATH (???), which I guess was not the case for 22.04 (but is for 24.04). Instead of pinning to an older image, I think moving forward we will need to explicitly request for
> 
> with: python-version: 3.x
> 
> as seen here: [pre-commit/action#210](https://github.com/pre-commit/action/issues/210). Thoughts?

Yep, this works. Fixed!

**Comment by peytondmurray** [comment]
Awesome, thank you!

**Pull request merged**
