### PR TITLE
Fix automatic creation of groups on setitem

### PR DESCRIPTION
**Pull request by asmeurer**
This matches the h5py behavior.

### CODE REVIEW

**Comment by scopatz** [comment]
Seems as though there is a conflict

**Comment by scopatz** [comment]
Thanks for this @asmeurer. Can we disable the inline code-cov, it is pretty annoying.

**Comment by scopatz** [comment]
And also seems wrong.

**Comment by asmeurer** [comment]
Oof, when did it start doing that?

**Comment by scopatz** [comment]
I don't know, this is the first time I have seen it.

**Pull request merged**
