### PR TITLE
Allow deleting groups between versions

### LINKED ISSUE #131: Deleting datasets
We need to support deleting datasets/groups and recreating them in later versions.

### PR DESCRIPTION
**Pull request by asmeurer**
Deleting datasets was already supported, but not tested.

This works as long as the dimensionality or dtype does not change between
versions. Changing the dtype would be possible, but would require some work.
Changing the dimensionality would be more difficult.

Fixes #131.

### CODE REVIEW

**Comment by scopatz** [comment]
Seems as though there is a conflict here now

**Comment by ArvidJB** [comment]
Thanks, that was really quick. It mostly works except for strings:
```
with h5py.File('foo.h5', 'w') as f:
    vf = VersionedHDF5File(f)
    with vf.stage_version('0') as sv:
        dtype = h5py.special_dtype(vlen=bytes)
        sv.create_dataset('bar/baz', data=['aaa'], dtype=dtype)

with h5py.File('foo.h5', 'r+') as f:
    vf = VersionedHDF5File(f)
    with vf.stage_version('1') as sv:
        del sv['bar']
        sv.create_dataset('bar/baz', data=['bbb'], dtype=dtype)
```
gives me the following error
```
Traceback (most recent call last):
  File "/u/bessen/opensource/versioned-hdf5/bytes_array_fillvalue.py", line 15, in <module>
    sv.create_dataset('bar/baz', data=['bbb'], dtype=dtype)
  File "/opt/python/python-3.7/lib64/python3.7/contextlib.py", line 119, in __exit__
    next(self.gen)
  File "/u/bessen/opensource/versioned-hdf5/versioned_hdf5/api.py", line 171, in stage_version
    timestamp=timestamp)
  File "/u/bessen/opensource/versioned-hdf5/versioned_hdf5/versions.py", line 102, in commit_version
    fillvalue=fillvalue)
  File "/u/bessen/opensource/versioned-hdf5/versioned_hdf5/backend.py", line 85, in write_dataset
    raise ValueError(f"fillvalues do not match ({fillvalue} != {ds.fillvalue})")
ValueError: fillvalues do not match (b'' != None)
```

**Comment by asmeurer** [comment]
It looks like this bug is unrelated to deleting (it happens on master too if you remove the `del` line and use `sv['bar/baz'] = ['bbb']`). Actually, deleting a group or dataset and recreating it in the same `stage_version` block should have no effect and ought to work even in master.

**Comment by asmeurer** [comment]
I guess in that case, you don't actually specify the fillvalue, which confuses it. You can use `sv['bar/baz'][()] = ['bbb']`, which does work.

**Comment by asmeurer** [comment]
I pushed a fix for it.

**Comment by scopatz** [comment]
Thanks

**Pull request merged**
