### PR TITLE
Disallow writes outside of the context manager

### LINKED ISSUE #5: Disallow writes outside of the context manager

### PR DESCRIPTION
**Pull request by asmeurer**
InMemoryDataset and InMemoryArrayDataset now require the parent InMemoryGroup
to construct, so that they can check the committed property before allowing
writing.

Fixes #5.

### CODE REVIEW

**Comment by asmeurer** [comment]
This will have merge conflicts with #72

**Comment by scopatz** [comment]
Which should be merged first?

**Comment by asmeurer** [comment]
It doesn't matter. The merge conflict resolution will be the same either way.

**Comment by scopatz** [comment]
Thanks!

**Pull request merged**
