### PR TITLE
Fixing things for h5py 3

### PR DESCRIPTION
**Pull request by asmeurer**
h5py 3.10 is out now, and there are several test failures. I've also added a CI build for Python 3.7 + h5py 2.10, which as I understand it is the configuration currently used internally at DEShaw (correct me if this is wrong), and I added CI tests for Python 3.9.

### CODE REVIEW

**Comment by asmeurer** [comment]
One of the errors here looks suspiciously like https://github.com/deshaw/versioned-hdf5/pull/125#issuecomment-673297722

```py
____________________________________________________________________ test_resize_multiple_dimensions ____________________________________________________________________

tmp_path = PosixPath('/private/var/folders/wc/dppcpmxs1tlb36nqcw853wkm0000gn/T/pytest-of-aaronmeurer/pytest-12/test_resize_multiple_dimension0')
h5file = <HDF5 file "file.hdf5" (mode r+)>

    def test_resize_multiple_dimensions(tmp_path, h5file):
        # Test semantics against raw HDF5

        vfile = VersionedHDF5File(h5file)
        shapes = range(5, 25, 5)  # 5, 10, 15, 20
        chunks = (10, 10, 10)
        for i, (oldshape, newshape) in\
                enumerate(itertools.combinations_with_replacement(itertools.product(shapes, repeat=3), 2)):
            data = np.arange(np.product(oldshape)).reshape(oldshape)
            # Get the ground truth from h5py
            vfile.f.create_dataset(f'data{i}', data=data, fillvalue=-1, chunks=chunks,
                                   maxshape=(None, None, None))
            vfile.f[f'data{i}'].resize(newshape)
            new_data = vfile.f[f'data{i}'][()]

            # resize after creation
            with vfile.stage_version(f'version1_{i}') as group:
                group.create_dataset(f'dataset1_{i}', data=data, chunks=chunks,
                                     fillvalue=-1)
                group[f'dataset1_{i}'].resize(newshape)
                assert group[f'dataset1_{i}'].shape == newshape
                assert_equal(group[f'dataset1_{i}'][()], new_data)

            version1 = vfile[f'version1_{i}']
            assert version1[f'dataset1_{i}'].shape == newshape
            assert_equal(version1[f'dataset1_{i}'][()], new_data)

            # resize in a new version
            with vfile.stage_version(f'version2_1_{i}', '') as group:
                group.create_dataset(f'dataset2_{i}', data=data, chunks=chunks,
                                     fillvalue=-1)
            with vfile.stage_version(f'version2_2_{i}', f'version2_1_{i}') as group:
                group[f'dataset2_{i}'].resize(newshape)
                assert group[f'dataset2_{i}'].shape == newshape
                assert_equal(group[f'dataset2_{i}'][()], new_data, str((oldshape, newshape)))

            version2_2 = vfile[f'version2_2_{i}']
            assert version2_2[f'dataset2_{i}'].shape == newshape
            assert_equal(version2_2[f'dataset2_{i}'][()], new_data)

            # resize after some data is read in
            with vfile.stage_version(f'version3_1_{i}', '') as group:
                group.create_dataset(f'dataset3_{i}', data=data, chunks=chunks,
                                     fillvalue=-1)
            with vfile.stage_version(f'version3_2_{i}', f'version3_1_{i}') as group:
                # read in first and last chunks
                group[f'dataset3_{i}'][0, 0, 0]
                group[f'dataset3_{i}'][-1, -1, -1]
                group[f'dataset3_{i}'].resize(newshape)
                assert group[f'dataset3_{i}'].shape == newshape
                assert_equal(group[f'dataset3_{i}'][()], new_data)

            version3_2 = vfile[f'version3_2_{i}']
            assert version3_2[f'dataset3_{i}'].shape == newshape
            assert_equal(version3_2[f'dataset3_{i}'][()], new_data)

        vfile.close()
        try:
>           h5file.close()

versioned_hdf5/tests/test_api.py:583:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
../../anaconda3/lib/python3.7/site-packages/h5py/_hl/files.py:445: in close
    id_list = h5f.get_obj_ids(self.id, ~h5f.OBJ_FILE)
h5py/_objects.pyx:54: in h5py._objects.with_phil.wrapper
    ???
h5py/_objects.pyx:55: in h5py._objects.with_phil.wrapper
    ???
h5py/h5f.pyx:275: in h5py.h5f.get_obj_ids
    ???
h5py/h5i.pyx:38: in h5py.h5i.wrap_identifier
    ???
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

>   ???
E   RuntimeError: Unspecified error in H5Iget_type (return value <0)

h5py/defs.pyx:1218: RuntimeError
```

**Comment by asmeurer** [comment]
Yeah, the test script https://github.com/deshaw/versioned-hdf5/pull/125#issuecomment-673298657 now gives this error

```
Traceback (most recent call last):
  File "test.py", line 14, in <module>
    run()
  File "test.py", line 11, in run
    g.create_dataset('a/' + str(i), data=list(range(1000)))
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/Users/aaronmeurer/anaconda3/lib/python3.7/site-packages/h5py/_hl/files.py", line 475, in __exit__
    self.close()
  File "/Users/aaronmeurer/anaconda3/lib/python3.7/site-packages/h5py/_hl/files.py", line 445, in close
    id_list = h5f.get_obj_ids(self.id, ~h5f.OBJ_FILE)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 275, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 38, in h5py.h5i.wrap_identifier
  File "h5py/defs.pyx", line 1218, in h5py.defs.H5Iget_type
RuntimeError: Unspecified error in H5Iget_type (return value <0)
```

which means it wasn't really fixed upstream.

**Comment by asmeurer** [comment]
Bisected the h5py to where it starts giving the error again to https://github.com/h5py/h5py/commit/ffc4cbf0437b1036779b785d2f7d1fe6c9d40c09

Based on the commit message, the error was being silenced before but was fixed to not be silenced.

**Comment by ArvidJB** [comment]
Thanks for looking into this. Yes, we are still on h5py 2.10.0. Right now we don't have any plans to upgrade since we'd probably have to move off Python 2.7 completely.

**Comment by asmeurer** [comment]
This is working now.

**Pull request merged**
