### PR TITLE
Added string datasets support (shape-0 arrays)

### PR DESCRIPTION
**Pull request by melissawm**
One difference between this and h5py is that 
```
f = h5py.File('file.h5', 'w')
f['bar'] = b'bar'
```
makes `f['bar']` into a `<HDF5 dataset "bar": shape (), type "|O">` (the dataset has dtype object) while 
```
vf = VersionedHDF5File(f)
with vf.stage_version('version1') as group:
    group['string_ds'] = b'baz'
```
results in a dataset with dtype S.

### CODE REVIEW

**Comment by asmeurer** [comment]
I'm afraid this will need to be redone now that #72 is merged. Hopefully it isn't too hard. Let me know if you have any issues. 

It looks like this fails if you try to create a second version, because it expects the dataset to be a virtual dataset.

```py
>>> with file.stage_version('version1') as group:
...     group['scalar_ds'] = 0
>>> with file.stage_version('version2') as group:
...     print(group['scalar_ds'])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/aaronmeurer/anaconda3/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "./versioned_hdf5/api.py", line 160, in stage_version
    prev_version=prev_version)
  File "./versioned_hdf5/versions.py", line 46, in create_version_group
    prev_group.visititems(_get)
  File "/Users/aaronmeurer/anaconda3/lib/python3.7/site-packages/h5py/_hl/group.py", line 565, in visititems
    return h5o.visit(self.id, proxy)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5o.pyx", line 355, in h5py.h5o.visit
  File "h5py/defs.pyx", line 1641, in h5py.defs.H5Ovisit_by_name
  File "h5py/h5o.pyx", line 302, in h5py.h5o.cb_obj_simple
  File "/Users/aaronmeurer/anaconda3/lib/python3.7/site-packages/h5py/_hl/group.py", line 564, in proxy
    return func(name, self[name])
  File "./versioned_hdf5/versions.py", line 40, in _get
    group[name] = item
  File "./versioned_hdf5/wrappers.py", line 91, in __setitem__
    self._data[name] = InMemoryDataset(obj.id)
  File "./versioned_hdf5/wrappers.py", line 319, in __init__
    super().__init__(InMemoryDatasetID(bind.id), **kwargs)
  File "./versioned_hdf5/wrappers.py", line 435, in __init__
    for j in range(dcpl.get_virtual_count())]
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5p.pyx", line 836, in h5py.h5p.PropDCID.get_virtual_count
ValueError: Not a virtual storage layout (not a virtual storage layout)
```

Also it would be good to add tests for other types of scalars than just byte strings.

**Comment by melissawm** [comment]
While trying to investigate the failure to create a second version as pointed out in the comments of PR #96, I found out that there is a HDF5 bug related to scalar datasets: https://github.com/h5py/h5py/issues/1409 

See #24  for details.  This is a partial workaround, and feedback is welcome!

**Comment by asmeurer** [comment]
Is this ready to review? How does it workaround the problem?

**Comment by melissawm** [comment]
I'm not sure it's ready, but I'd like some feedback. I'm not sure if it solves the problem entirely. Right now, due to the HDF5 bug, the situation is as follows:

```python
In [1]: import h5py; from versioned_hdf5 import VersionedHDF5File                                   

In [2]: f = h5py.File('test.h5', 'w'); file = VersionedHDF5File(f)                                  

In [3]: with file.stage_version('version1') as group: 
   ...:     group['scalar_ds'] = b'baz' 
   ...:                                                                                             

In [4]: file['version1']['scalar_ds']                                                               
Out[4]: <InMemoryArrayDataset "scalar_ds": shape (), type "|S3">

In [5]: file['version1']['scalar_ds'][()]                                                           
Out[5]: b'baz'
```
This works as expected; the shape of the dataset is `()`, but the byte-string has been converted to a NumPy 'S' dtype.

However:
```python
In [6]: f['_version_data/versions']['version1']['scalar_ds']                                        
Out[6]: <HDF5 dataset "scalar_ds": shape (1,), type "|S3">
```
The virtual dataset has shape `(1,)`, as otherwise we couldn't link the VirtualLayout to the VirtualSource. Also, if we try to access the 0-shaped array directly using the HDF5 API, we get 
```python
In [7]: f['_version_data/versions']['version1']['scalar_ds'][()]                                    
Floating point exception (core dumped)
```
This is the bug I mentioned above.

**Comment by asmeurer** [comment]
I think it will be more robust to just copy scalar datasets, meaning don't make them virtual at all. There are a few places in the code that assume a dataset is virtual that would need to be updated.  Hopefully not too many. If the bug in the upstream is ever fixed, we can modify it to use virtual datasets again. 

The only concern is if this would lead to too large of a memory footprint, since every version would have every scalar dataset copied in the file. It sounds like DEShaw is using large byte strings, so this could be an issue. If so, then I think what we have here is fine. We already specify that you should only use the versioned_hdf5 API to access versioned files. We just need to be careful whenever we read through virtual datasets in library code to check if they are scalar.

**Comment by asmeurer** [comment]
As discussed in the meeting today, this should be good enough for now.

**Pull request merged**
