### PR TITLE
Skip health checks in build_data_dict

### LINKED ISSUE #356: Slicetools platform-specific error `could not get virtual filename`
Likely related to #352 - the following is broken on Linux (but not Mac) with the latest commit on `master`:

```python
import h5py
from versioned_hdf5 import VersionedHDF5File
import numpy as np


d = './testdata.h5'

with h5py.File(d, mode="w") as f:
    vf = VersionedHDF5File(f)
    with vf.stage_version("r0") as sv:
        sv.create_dataset('values', data=np.arange(100), chunks=(10,), maxshape=(None,))

with h5py.File(d, mode="r+") as f:
    vf = VersionedHDF5File(f)
    with vf.stage_version("r1") as sv:
        values = sv['values']
        values.resize((110,))  # <-- Exception raised here
```

With `h5py==3.11.0` I get the following:

```
HDF5-DIAG: Error detected in HDF5 (1.14.4-3) thread 0:
  #000: H5Pdcpl.c line 2406 in H5Pget_virtual_filename(): can't find object for ID
    major: Object ID
    minor: Unable to find ID information (already closed?)
  #001: H5Pint.c line 4102 in H5P_object_verify(): property list is not a member of the class
    major: Property lists
    minor: Can't compare objects
  #002: H5Pint.c line 4053 in H5P_isa_class(): not a property list
    major: Invalid arguments to routine
    minor: Inappropriate type
Traceback (most recent call last):
  File "/home/pdmurray/Desktop/workspace/sandbox/vhdf/run.py", line 20, in <module>
    values.resize((110,))  # <-- Exception raised here
    ^^^^^^^^^^^^^^^^^^^^^
  File "/home/pdmurray/Desktop/workspace/versioned-hdf5/versioned_hdf5/wrappers.py", line 777, in resize
    data_dict = self.id.data_dict
                ^^^^^^^^^^^^^^^^^
  File "/home/pdmurray/Desktop/workspace/versioned-hdf5/versioned_hdf5/wrappers.py", line 1451, in data_dict
    self._data_dict = build_data_dict(dcpl, self.raw_data.name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "slicetools.pyx", line 128, in versioned_hdf5.slicetools.build_data_dict
  File "slicetools.pyx", line 144, in versioned_hdf5.slicetools.build_data_dict
  File "slicetools.pyx", line 168, in versioned_hdf5.slicetools.build_data_dict
ValueError: Could not get virtual filename
```

### PR DESCRIPTION
**Pull request by crusaderky**
Closes #356

### CODE REVIEW

**Comment by crusaderky** [comment]
@peytondmurray let me know if this solves your issues

**Comment by crusaderky** [comment]
Alternatively, here you can find a function to print out what's wrong: https://github.com/crusaderky/versioned-hdf5/blob/6cf34ada3157095ed185ae1f41507c55a012006e/versioned_hdf5/slicetools.pyx#L642-L654

**Comment by peytondmurray** [comment]
Sadly this doesn't solve the issue:

```
HDF5-DIAG: Error detected in HDF5 (1.14.4-3) thread 0:
  #000: H5Pdcpl.c line 2252 in H5Pget_virtual_vspace(): can't find object for ID
    major: Object ID
    minor: Unable to find ID information (already closed?)
  #001: H5Pint.c line 4102 in H5P_object_verify(): property list is not a member of the class
    major: Property lists
    minor: Can't compare objects
  #002: H5Pint.c line 4053 in H5P_isa_class(): not a property list
    major: Invalid arguments to routine
    minor: Inappropriate type
Traceback (most recent call last):
  File "/home/pdmurray/Desktop/workspace/sandbox/vhdf/testing.py", line 17, in <module>
    sv['values'].resize((110,))  # <-- Exception raised here
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pdmurray/.pyenv/versions/vhdf/lib/python3.11/site-packages/versioned_hdf5/wrappers.py", line 736, in resize
    data_dict = self.id.data_dict
                ^^^^^^^^^^^^^^^^^
  File "/home/pdmurray/.pyenv/versions/vhdf/lib/python3.11/site-packages/versioned_hdf5/wrappers.py", line 1416, in data_dict
    self._data_dict = build_data_dict(dcpl, self.raw_data.name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "slicetools.pyx", line 139, in versioned_hdf5.slicetools.build_data_dict
  File "slicetools.pyx", line 154, in versioned_hdf5.slicetools.build_data_dict
  File "slicetools.pyx", line 162, in versioned_hdf5.slicetools.build_data_dict
ValueError: Could not get vspace_id
```

It just throws an error later on when you call `H5Pget_virtual_vspace`. While the health checks are definitely unnecessary here, something else is going on with the `dcpl_id` on certain platforms. Let me make a Docker image for reproducing this.

**Comment by crusaderky** [comment]
>  I actually cannot inspect the output of H5Pget_virtual_filename because it is of type ssize_t, not herr_t
Doesn't matter, you got a -1 error code you just run my function to get the proper error message.

**Comment by crusaderky** [comment]
@peytondmurray Try now. You should get a proper error message.

**Comment by crusaderky** [comment]
Demo for the new error function:
```
Traceback (most recent call last):
  File "/home/crusaderky/nfs/sync_lea/Quansight/hdf5_read/npindices.py", line 255, in <module>
    read_many_slices(
  File "slicetools.pyx", line 287, in versioned_hdf5.slicetools.read_many_slices
  File "slicetools.pyx", line 458, in versioned_hdf5.slicetools.read_many_slices
  File "slicetools.pyx", line 570, in versioned_hdf5.slicetools._read_many_slices_fast
  File "slicetools.pyx", line 625, in versioned_hdf5.slicetools._read_many_slices_fast
RuntimeError: HDF5-DIAG: Error detected in HDF5 (1.14.3) thread 1:
  #000: H5D.c line 1061 in H5Dread(): can't synchronously read data
    major: Dataset
    minor: Read failed
  #001: H5D.c line 977 in H5D__read_api_common(): dset_id is not a dataset ID
    major: Invalid arguments to routine
    minor: Inappropriate type
```

**Review by peytondmurray — APPROVED** [review]
Oh, I see - there's a global HDF5 error stack, so there's no need to examine the error code returned by libhdf5 function calls. Thanks for this!

**Pull request merged**
