### PR TITLE
Garbage collect closed groups

### LINKED ISSUE #121: Memory leak
There are some leaks somewhere where you eventually run out of memory.

### LINKED ISSUE #122: Trailing slash in __contains__
We have some code that checks whether `'a/b/' in group` which currently does not work:
```
with h5py.File('foo.h5', 'w') as f:
    vf = VersionedHDF5File(f)
    with vf.stage_version('v0') as sv:
        sv.create_group('a/b')
        sv['a/b/c'] = np.array([1, 2, 3])

with h5py.File('foo.h5', 'r+') as f:
    vf = VersionedHDF5File(f)
    r = vf[vf.current_version]
    assert 'a' in r
    assert 'a/' in r
    assert 'a/b' in r
    assert 'a/b/' in r
    assert 'a/b/c' in r
```

### PR DESCRIPTION
**Pull request by asmeurer**
This should fix the memory leak issues (fixes #121). @ArvidJB let me know if you still have memory leaking issues with this PR.

Also fixes trailing slashes in `__contains__` (fixes #122).

### CODE REVIEW

**Comment by asmeurer** [comment]
I can sometimes get errors like this with this branch

```pytb
  File "test.py", line 16, in <module>
    run()
  File "test.py", line 11, in run
    g.create_dataset('a/' + str(i), data=list(range(1000)))
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/Users/aaronmeurer/anaconda3/lib/python3.7/site-packages/h5py/_hl/files.py", line 461, in __exit__
    self.close()
  File "/Users/aaronmeurer/anaconda3/lib/python3.7/site-packages/h5py/_hl/files.py", line 431, in close
    id_list = h5f.get_obj_ids(self.id, ~h5f.OBJ_FILE)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 267, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 55, in h5py.h5i.wrap_identifier
ValueError: Unrecognized type code -1
```

I'm not sure what it means.

**Comment by asmeurer** [comment]
That error goes away if I use the git version of h5py. So I'm assuming it's a bug there. Hopefully you don't hit it at DEShaw, but if you do, I can try bisecting the h5py commit. This is the test script I used

```py
import h5py
from versioned_hdf5 import VersionedHDF5File

N = 200
def run():
    with h5py.File('test.hdf5', 'w') as f:
        file = VersionedHDF5File(f)
        for i in range(N):
            print(f'{i}/{N}')
            with file.stage_version(str(i), '') as g:
                g.create_dataset('a/' + str(i), data=list(range(1000)))

if __name__ == '__main__':
    run()
```

**Comment by asmeurer** [comment]
It was fixed by 773680edcfd868a32a2b047ad654fb3d28da92b2, which I don't understand.

**Comment by ArvidJB** [comment]
Thanks, I will try it out!

I have never seen this weird `ValueError: Unrecognized type code -1`...

**Comment by scopatz** [comment]
Seems like there is a significant merge conflict here @asmeurer. Can you please take a look?

**Comment by asmeurer** [comment]
I fixed the merge conflicts.

**Comment by asmeurer** [comment]
I guess the new test fixtures have brought out this weird `Unrecognized type code -1` error. I suspect it means things are being garbage collected too soon.

**Comment by scopatz** [comment]
CI is failing

**Comment by asmeurer** [comment]
Might need some help debugging this. There is some sort of condition where the garbage collector frees HDF5 objects and then `close()` tries to free them again. I can't tell what exactly is happening, or if it is a bug in versioned_hdf5 or h5py. The above h5py commit that "fixes" the problem question adds some caching, suggesting that it only fixes it because it keeps some references around for longer.

**Comment by asmeurer** [comment]
The exception here happens when the h5py file is being closed, not in the versioned_hdf5 code. For now, we can work around it in our test suite by using

```py
f = h5py.File(...)
...
try:
    f.close()
except:
    pass
```

instead of using h5py.File as a context manager.

**Comment by asmeurer** [comment]
I've worked around the failure in our test suite. The agreed plan was to merge this for now, and if the issue comes up later we can investigate further, or see if it will be necessary to backport the h5py fix.

**Pull request merged**
