### PR TITLE
Support for storing binary data as void

### LINKED ISSUE #69: fillvalue and void dtypes
We try to write empty binary data to HDF5 which now fails with the changes in #60 :
```
import h5py
import numpy as np
from versioned_hdf5 import VersionedHDF5File

with h5py.File('foo.h5', 'w') as f:
    vf = VersionedHDF5File(f)
    with vf.stage_version('0') as sv:
        sv['bar'] = [np.void(b' ')]
```
in
```
  File "/u/bessen/opensource/versioned-hdf5/versioned_hdf5/wrappers.py", line 338, in __init__
    self.fillvalue = fillvalue or array.dtype.type()
TypeError: void() takes exactly 1 argument (0 given)
```

### PR DESCRIPTION
**Pull request by ArvidJB**
This fixes #69. Storing void data is kind of weirdly supported by h5py
and we seem to use this particular corner case.

### CODE REVIEW

**Comment by asmeurer** [comment]
So this means that void datasets cannot be resized?

**Comment by asmeurer** [comment]
It looks like they can and it uses nulls as the default fillvalue. 

```py
>>> f = h5py.File('test.hdf5', 'w')
>>> f.create_dataset('data', chunks=(1,), maxshape=(None,), data = [np.void(b'1111')])
<HDF5 dataset "data": shape (1,), type "|V4">
>>> f['data'].resize((2,))
>>> f['data'][:]
array([b'\x31\x31\x31\x31', b'\x00\x00\x00\x00'], dtype='|V4')
```

So maybe instead of using `dtype()` to get the default fillvalue we should use `np.zeros((1,), dtype=self.dtype)[0]`. 

```py
>>> np.zeros((1,), f['data'].dtype)[0]
void(b'\x00\x00\x00\x00')
```

**Comment by asmeurer** [comment]
Or just `np.zeros((), dtype=dtype)`.

**Comment by asmeurer** [comment]
I pushed that up as an alternate fix. It still passes your test.

**Comment by ArvidJB** [comment]
That's probably even better, let me try your suggestion.

**Comment by ArvidJB** [comment]
You probably want
```np.zeros((), array.dtype)[()]```
though, no? Otherwise the fillvalue is an array.

**Comment by asmeurer** [comment]
Shape `()` arrays are usually interchangeable for scalar objects, though there can be subtle corner cases. But the scalar would match the h5py behavior, so I've modified it like you suggested.

**Comment by melissawm** [comment]
Looks good, can we merge?

**Comment by asmeurer** [comment]
Sorry I mean to merge this earlier.

**Pull request merged**
