### PR TITLE
Continuing work on sparse datasets

### PR DESCRIPTION
**Pull request by asmeurer**
#63 was merged prematurely, so this continues that work.

### CODE REVIEW

**Comment by asmeurer** [comment]
I have it so that sparse data works, but only if you close and reopen the file before writing any non-fillvalue data. However, full support should not be much more work. I also haven't added any tests yet.

**Comment by asmeurer** [comment]
This is ready for testing and review. I think it might be a good idea to look into making the necessary improvements in ndindex to improve the performance here (currently any index on a dataset naively iterates over all chunks to see which ones contain the index). The performance is serviceable for the dataset shapes/chunk sizes described at https://github.com/deshaw/versioned-hdf5/pull/63#issuecomment-709315447, but I think it could still be noticable.

**Comment by scopatz** [comment]
CI seems to be failing

**Comment by scopatz** [comment]
I think this looks reasonable.

**Pull request merged**
